**.describe()**

O método .describe() em Python, quando utilizado em bibliotecas como Pandas, fornece um resumo estatístico das colunas numéricas de um DataFrame. Aqui está o que cada valor representa:
count: O número de valores não nulos em cada coluna. É útil para verificar se existem valores ausentes.
mean: A média aritmética dos valores. Isso dá uma ideia do valor central dos dados.
std: O desvio padrão, que mede a dispersão dos valores em relação à média. Um valor alto indica que os dados estão muito espalhados.
min: O menor valor presente na coluna.
25%: O primeiro quartil (Q1), que é o valor abaixo do qual 25% dos dados caem. Ele indica a mediana da primeira metade dos dados.
50%: A mediana (Q2), que é o valor que divide os dados ao meio. 50% dos dados estão abaixo e 50% estão acima desse valor.
75%: O terceiro quartil (Q3), que é o valor abaixo do qual 75% dos dados caem. Ele indica a mediana da segunda metade dos dados.
max: O maior valor presente na coluna.
Esses valores ajudam a entender a distribuição e a tendência central dos dados em um DataFrame, facilitando a análise estatística e a identificação de outliers.
 

**Atividade 1: Crie um array unidimensional com os números de 1 a 12. Transforme este array em uma matriz de 3 linhas e 4 colunas.(Desafio: Aplique a tarnsposição da matriz para criar as dimensões em 4x3 (.transpose)e, em seguida, crie um array unidimensional (.flatten))**


In [1]:
import pandas as pd
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
matrizR=arr.reshape(3,4)
matrizT=matrizR.transpose()
arrayF=matrizT.flatten()

print(f"------Array Original------\n{arr}")
print(f"------Reshape------\n{matrizR}")
print(f"------Transpose------\n{matrizT}")
print(f"------Flatten------\n{arrayF}")

------Array Original------
[ 1  2  3  4  5  6  7  8  9 10 11 12]
------Reshape------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------Transpose------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
------Flatten------
[ 1  5  9  2  6 10  3  7 11  4  8 12]


**Atividade 2: Leia o arquivo ClassicDisco.csv trabalhando em aulas anteriores e aplique o comando .describe() para gerar uma análise estatística das ultimas linhas do Dataset com apoio nesta atividade.**


In [5]:
df_disco = pd.read_csv('C:\\Users\\unidade.copacabana\\Documents\\BigDataSenac\\arquivos\\ClassicDisco.csv')
print(df_disco.tail().describe())

         Year       Duration  Time_Signature  Danceability    Energy  \
count     5.0       5.000000             5.0      5.000000  5.000000   
mean   1979.0  322579.000000             4.0      0.659200  0.907400   
std       0.0   80231.120066             0.0      0.032097  0.062304   
min    1979.0  208200.000000             4.0      0.633000  0.840000   
25%    1979.0  299510.000000             4.0      0.633000  0.854000   
50%    1979.0  306818.000000             4.0      0.649000  0.901000   
75%    1979.0  390567.000000             4.0      0.672000  0.970000   
max    1979.0  407800.000000             4.0      0.709000  0.972000   

             Key  Loudness  Mode  Speechiness  Acousticness  Instrumentalness  \
count   5.000000   5.00000   5.0      5.00000      5.000000          5.000000   
mean    6.000000  -6.35860   1.0      0.05708      0.011308          0.223529   
std     3.082207   2.57186   0.0      0.04591      0.022023          0.392843   
min     2.000000 -10.24800 