##Aula 05##

In [2]:
import numpy as np
import pandas as pd

In [3]:
#convertendo um array para uma série
arr1=np.array([10,20,30])
serie1=pd.Series(arr1)
print(arr1)
print(serie1)


[10 20 30]
0    10
1    20
2    30
dtype: int64


In [4]:
arr2= serie1.to_numpy()
print(arr2)

[10 20 30]


**Dataframes e suas principais funções**

In [39]:
#Criacao
arr3=np.array([[1,2],[3,4]])
df_arr=pd.DataFrame(arr3,columns=['A','B'])
print(arr3)
print(df_arr)

[[1 2]
 [3 4]]
   A  B
0  1  2
1  3  4


In [40]:
#Transformando uma coluna em uma série
coluna_serie=df_arr3['A']
print(coluna_serie)

0    1
1    3
Name: A, dtype: int64


In [41]:
#Contagem de valores
estados=pd.DataFrame({'Cidade': ['RJ', 'SP', 'MG', 'ES', 'RJ', 'RJ', 'SP']})
print(estados['Cidade'].value_counts())

Cidade
RJ    3
SP    2
MG    1
ES    1
Name: count, dtype: int64


In [42]:
#Calculos Estatísticos
notas=pd.DataFrame({'Notas':[10, 8.5,7,7,7,7,5.6,6,8,8,7,9,10,9,8.5]})
print(notas['Notas'].sum()) #soma
print(notas['Notas'].mean()) #média
print(notas['Notas'].median()) #mediana
print(notas.describe()) #Resumo das estatísticas


117.6
7.84
8.0
