##Aula 05##

In [2]:
import numpy as np
import pandas as pd

In [3]:
#convertendo um array para uma série
arr1=np.array([10,20,30])
serie1=pd.Series(arr1)
print(arr1)
print(serie1)


[10 20 30]
0    10
1    20
2    30
dtype: int64


In [4]:
arr2= serie1.to_numpy()
print(arr2)

[10 20 30]


**Dataframes e suas principais funções**

In [39]:
#Criacao
arr3=np.array([[1,2],[3,4]])
df_arr=pd.DataFrame(arr3,columns=['A','B'])
print(arr3)
print(df_arr)

[[1 2]
 [3 4]]
   A  B
0  1  2
1  3  4


In [40]:
#Transformando uma coluna em uma série
coluna_serie=df_arr3['A']
print(coluna_serie)

0    1
1    3
Name: A, dtype: int64


In [41]:
#Contagem de valores
estados=pd.DataFrame({'Cidade': ['RJ', 'SP', 'MG', 'ES', 'RJ', 'RJ', 'SP']})
print(estados['Cidade'].value_counts())

Cidade
RJ    3
SP    2
MG    1
ES    1
Name: count, dtype: int64


In [42]:
#Calculos Estatísticos
notas=pd.DataFrame({'Notas':[10, 8.5,7,7,7,7,5.6,6,8,8,7,9,10,9,8.5]})
print(notas['Notas'].sum()) #soma
print(notas['Notas'].mean()) #média
print(notas['Notas'].median()) #mediana
print(notas.describe()) #Resumo das estatísticas


117.6
7.84
8.0


**Atividade 1: 
Crie um array unidimensional com os números de 1 a 12. Transforme este array em uma matriz de 3 linhas e 4 colunas.(Desafio: Aplique a tarnsposição da matriz para criar as dimensões em 4x3 (.transpose)e, em seguida, crie um array unidimensional (.flatten))**

In [58]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
matrizR=arr.reshape(3,4)
matrizT=matriz.transpose()
arrayF=matrizT.flatten()

print("------Array Original------\n", arr)
print("------Reshape------\n", matrizR)
print("------Transpose------\n", matrizT)
print("------Flatten------\n", arrayF)




------Array Original------
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
------Reshape------
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------Transpose------
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
------Flatten------
 [ 1  5  9  2  6 10  3  7 11  4  8 12]


**Atividade 2: 
Leia o arquivo ClassicDisco.csv trabalhando em aulas anteriores e aplique o comando .describe() para gerar uma análise estatística das ultimas linhas do Dataset com apoio nesta atividade.**

In [66]:

df_disco = pd.read_csv('C:\\Users\\unidade.copacabana\\Documents\\BigDataSenac\\arquivos\\ClassicDisco.csv')
print(df_disco.tail().describe())

         Year       Duration  Time_Signature  Danceability    Energy  \
count     5.0       5.000000             5.0      5.000000  5.000000   
mean   1979.0  322579.000000             4.0      0.659200  0.907400   
std       0.0   80231.120066             0.0      0.032097  0.062304   
min    1979.0  208200.000000             4.0      0.633000  0.840000   
25%    1979.0  299510.000000             4.0      0.633000  0.854000   
50%    1979.0  306818.000000             4.0      0.649000  0.901000   
75%    1979.0  390567.000000             4.0      0.672000  0.970000   
max    1979.0  407800.000000             4.0      0.709000  0.972000   

             Key  Loudness  Mode  Speechiness  Acousticness  Instrumentalness  \
count   5.000000   5.00000   5.0      5.00000      5.000000          5.000000   
mean    6.000000  -6.35860   1.0      0.05708      0.011308          0.223529   
std     3.082207   2.57186   0.0      0.04591      0.022023          0.392843   
min     2.000000 -10.24800 